version: "3.7"
services:
  api:
    container_name: api
    build: ./api
    environment:
      PG_CONNECTION_STRING: postgres://admin:dev5@festival_db:5432/festival_api
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/usr/app/api/src


  db:
    container_name: festival_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dev5
      POSTGRES_USER: admin
      POSTGRES_DB: festival_api
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432